### ISSUE TITLE
Is there documentation on how to use the deployed version?

### ISSUE THREAD

**Issue by entmike** [saphanaacademy/xsahaa#1]
Hey guys.  I was able to deploy xsahaa using the .tar.gz found in this .zip:

`https://tools.hana.ondemand.com/additional/xsahaa-onprem-1.4.0-XSACHAADP04_0.zip`

It deployed without issue, however when trying to test the INA url like so:

`https://ipaper-sandbox-xsahaa-entry.bwsxsa.sap.ipaper.com:36133/sap/bc/ina/service/v2/GetServerInfo`

I get this error:

```
{"Messages":[{"Type":2,"Number":0,"Text":"com.sap.db.jdbc.exceptions.SQLInvalidAuthorizationSpecExceptionSapDB: [10]: authentication failed"}]}
```

Any thoughts?  Is there a guide?  Thanks.

**Comment by saphanaacademy** [comment]
Hi Mike,
The steps for HANA service in SCP are shown in this video: https://www.youtube.com/watch?v=IwYNU1tNiEo&index=24&t=0s&list=PLkzo92owKnVyh290bEmKED11Gcdkyoi7w 
Otherwise there is some limited documentation in the RELEASE_NOTES.md file of https://tools.hana.ondemand.com/additional/xsahaa-release-1.4.0-release.zip 
I'm not aware of any guide for the onprem version however. I suggest asking on the SAP community: https://answers.sap.com/questions/ask.html with tag SAP HANA Info Access.
Thanks,
Philip
